const getContentByCategoryEndPoint = '/genre/'
const getContentByDirectorEndPoint = '/director/'
const getContentByCountryEndPoint = '/country/'
const getContentBySearchEndPoint = '/?s='
const getAdultContentEndpoint = '/account/?ptype=post&tax_quality=' //18&wpas=1
//https://hindilinks4u.lat/account/?ptype=post&tax_quality=18&tax_release-year=2022&wpas=1
//"d2ec9fd8a28f462f8e5b6a2378749891",

const categories = [
  'erotic-movies',
  'dual-audio',
  'bollywood',
  'hollywood',
  'web-series',
  'comedy',
  'drama',
  'action',
  'adventure',
  'animation',
  'biography',
  'comedy',
  'crime',
  'drama',
  'music',
  'mystery',
  'family',
  'fantasy',
  'horror',
  'history',
  'romantic',
  'science-fiction',
  'thriller',
  'war',
  'south-special',
  'bengali',
  'marathi',
  'gujarati',
  'punjabi',
  'kannada',
  'tamil',
  'telugu',
  'malayalam',
  'tv-shows',
] //genre

const animeCategories = [
  'action',
  'adventure',
  'cars',
  'comedy',
  'crime',
  'dementia',
  'demons',
  'drama',
  'dub',
  'ecchi',
  'family',
  'fantasy',
  'game',
  'gourmet',
  'harem',
  'hentai',
  'historical',
  'horror',
  'josei',
  'kids',
  'magic',
  'martial-arts',
  'mecha',
  'military',
  'Mmusic',
  'mystery',
  'parody',
  'police',
  'psychological',
  'romance',
  'samurai',
  'school',
  'sci-fi',
  'seinen',
  'shoujo',
  'shoujo-ai',
  'shounen',
  'shounen-ai',
  'slice-of-Life',
  'space',
  'sports',
  'super-power',
  'supernatural',
  'suspense',
  'thriller',
  'vampire',
  'yaoi',
  'yuri',
  'isekai',
]
const searchKeyword = ['uncut', 'ullu', 'glamheart'] //s?
const director = [
  'netflix',
  'amazon-prime',
  'altbalaji',
  'zee5',
  'voot-originals',
  'mx-player',
  'hotstar',
  'viu-originals',
  'sonyliv-original',
  'fliz-movies',
  'nuefliks-exclusive',
  'hotshots',
  'kooku-originals',
  'gupchup-exclusive',
  'cinemadosti',
  'primeflix',
  'gemplex',
  'rabbit-original',
  'hotmasti-originals',
  'boommovies-original',
  'cliff-movies',
  'masti-prime-originals',
  'ek-night-show',
  'flixsksmovies',
  'lootlo-original',
  'hootzy-channel',
  'balloons-originals',
  'big-movie-zoo-originals',
  'bambooflix',
  'piliflix-originals',
  '11upmovies-originals',
  'eightshots-originals',
  'i-entertainment-exclusive',
  'hotprime-originals',
  'banana-prime',
  'hothitfilms',
  'chikooflix-originals',
  'worldprime-originals',
] //director
const country = ['india'] //country
const adultCategory = '18'
module.exports = {
  getContentByCategoryEndPoint,
  getContentByDirectorEndPoint,
  getContentByCountryEndPoint,
  getContentBySearchEndPoint,
  getAdultContentEndpoint,
  categories,
  animeCategories,
  searchKeyword,
  adultCategory,
  director,
  country,
}
